apiVersion: qbec.io/v1alpha1
kind: App
metadata:
  name: it-one
spec:
  environments:
    stage:
      defaultNamespace: default
      context: stage
    prod:
      defaultNamespace: default
      context: prod
  vars:
    computed:
      - name: helmTemplate
        code: |
          {
            local p = import './params.libsonnet',
            # TODO: how to iterate and call command for each object in array?
            local values = p.envs[0].components['ingress'].values,
            command: '../.bin/helm',
            args: [ 'template', p.envs[0].name, '../vendor', '-f-' ],
            stdin: std.manifestJson(values)
          }
  dataSources:
    # data sources are declared to be of the form
    #   <kind>://<name>?configVar=<configuration-variable-name>
    # in this case kind=exec, name=helm, and config var is helmTemplate defined above
    - exec://helm?configVar=helmTemplate